# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_content', models.TextField(max_length=500)),
                ('post_published', models.BooleanField(default=True)),
                ('post_created', models.DateTimeField(auto_now=True)),
                ('post_edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
